### PR TITLE
Redirected blackfriday url to working version

### PR DESCRIPTION
**Pull request by johncurley**
This seems to be the working URL for the import.

### CODE REVIEW

**Comment by imdario** [comment]
About the first commit: I have a small issue. I updated Zas to use go modules and gopkg.in/russross/blackfriday.v2 doesn't play well with them.

That's why I use github.com/russross/blackfriday/v2. Maybe @russross could help us to solve this :)

**Comment by johncurley** [comment]
Okay, that's fine. I wasn't aware that you had already converted the project to use Go modules. Feel free to just remove the commit.

**Comment by johncurley** [comment]
Closing pull request due to incompatibility.

**Comment by imdario** [comment]
What was your use of Zas? If it wasn't embedded in another project, I just released version 0.0.2 so you can use it as binary :)

**Pull request closed without merging**
